#!/usr/bin/env python
"""Stage a standalone pole-vec FULL-mode run dir from Stage-2 outputs.

Builds the exact layout ``PoleVec_workflow.py`` + the csv-seed inputconfig
expect when the run dir is mounted at /data:

    <run_dir>/
      02_pole_crop/output/crops_metric/<Pole_N>.las   (hardlinks to the crops)
      03_pole_vec_body/polevec_pole_tops.csv          (validated seed CSV)
      PoleVec_control_runtime.yml                     (FULL control, CRS set)

Validations (each failure is fatal unless noted):
  * every seed-CSV LAS_NAME resolves to a staged crop (after stripping
    ``las_end_str`` / ``_thinned``); rows that do not are DROPPED with a
    warning (pole-vec would skip them anyway, loudly and confusingly)
  * crops must be .las - las_end_str '.las' makes .laz invisible to pole-vec
  * CSV has the exact columns Pole, TOP_X, TOP_Y, TOP_Z, LAS_NAME

Prints the docker command to run afterwards.
"""
import argparse
import csv
import os
import shutil
import sys
from pathlib import Path

# The firmatek FULL control (md5-identical host checkout / sdai_chain_polevec
# volume, 2026-08-23) with CRS templated.  Every key is required by
# PoleVec_workflow.py - keep blanks blank, do not delete keys.
CONTROL_TEMPLATE = """\
# Runtime control generated by prepare_polevec_run.py (pole-network-catenary)
# Base: PoleVec_control_firmatek_metric_full.yml  |  FULL mode
estimate_pole_tops:
las_end_str: .las
estimate_pole_top_z: false
CRS: {crs}
OutputLAS_FileFormat: 1.4
OutputLAS_PointFormat: 7
convert_feet_to_meters: false
convert_results_to_feet: false
process_pole_body_data_first: true
stop_after_pole_body_estimation: false
save_time_data: true
processes_pole_body: true
process_transformer: true
process_wires: true
process_crossarms: true
combine_pole_vec_data: true
filter_wires: true
parallel_processing:
  las_files_num_threads: {threads}
  las_files_num_threads_pole_only: 21
  pole_num_threads: 1
  transformer_num_threads: 1
  wire_num_threads: 1
  crossarm_num_threads: 1
pole_top_csv_file: 03_pole_vec_body/polevec_pole_tops.csv
create_csv_file:
"""

DOCKER_CMD = """\
MSYS_NO_PATHCONV=1 docker run --rm --gpus all --shm-size=8gb \\
  -v sdai_chain_polevec:/app \\
  -v "{run_dir}":/data \\
  750433818015.dkr.ecr.us-west-2.amazonaws.com/mmworkflow:v1.8.0.1 \\
  python /app/PoleVec_workflow.py \\
    --input_inputconfig      /app/inputconfig_FIRMATEK_csv_seed.yml \\
    --input_folder           /data \\
    --input_inputcontrol     PoleVec_control_runtime.yml \\
    --input_segmented_folder 02_pole_crop/output/crops_metric
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--crops-dir", required=True, type=Path,
                    help="Stage-2 crops dir (metric CRS, .las)")
    ap.add_argument("--processed-csv", required=True, type=Path,
                    help="<stem>_processed.csv written next to the pole "
                         "shapefile by pipeline.py")
    ap.add_argument("--run-dir", required=True, type=Path)
    ap.add_argument("--crs", required=True, type=int,
                    help="EPSG integer of the crops (e.g. 26917). Stamped "
                         "into every pole-vec output - MUST match the crops")
    ap.add_argument("--las-threads", type=int, default=8,
                    help="las_files_num_threads in the control (lower to 2 "
                         "on OOM)")
    args = ap.parse_args()

    if not args.crops_dir.is_dir():
        sys.exit(f"crops dir not found: {args.crops_dir}")
    if not args.processed_csv.is_file():
        sys.exit(f"processed CSV not found: {args.processed_csv}")

    laz = list(args.crops_dir.glob("*.laz"))
    if laz:
        sys.exit(f"{len(laz)} .laz crop(s) in {args.crops_dir} - pole-vec's "
                 f"las_end_str '.las' cannot see them. Re-crop without "
                 f"--compress-intermediates or convert to .las first.")

    crops = sorted(args.crops_dir.glob("*.las"))
    if not crops:
        sys.exit(f"no .las crops in {args.crops_dir}")

    # --- stage crops -------------------------------------------------------
    crops_out = args.run_dir / "02_pole_crop" / "output" / "crops_metric"
    crops_out.mkdir(parents=True, exist_ok=True)
    staged = {}
    for crop in crops:
        dst = crops_out / crop.name
        if not dst.exists():
            try:
                os.link(crop, dst)
            except OSError:
                shutil.copy2(crop, dst)
        staged[crop.name] = dst
    print(f"staged {len(staged)} crop(s) -> {crops_out}")

    # --- seed CSV ----------------------------------------------------------
    def resolves(las_name: str):
        """Match a LAS_NAME to a staged crop the way pole-vec does."""
        base = las_name
        for ext in (".las", ".laz"):
            if base.lower().endswith(ext):
                base = base[: -len(ext)]
        for cand in (f"{base}.las",
                     f"{base}_thinned.las",
                     f"{base.removesuffix('_thinned')}.las"):
            if cand in staged:
                return cand
        return None

    with open(args.processed_csv, newline="") as fh:
        rows = list(csv.DictReader(fh))
    required = ["Pole", "TOP_X", "TOP_Y", "TOP_Z", "LAS_NAME"]
    if not rows:
        sys.exit(f"empty CSV: {args.processed_csv}")
    missing_cols = [c for c in required if c not in rows[0]]
    if missing_cols:
        sys.exit(f"CSV missing column(s) {missing_cols}; has "
                 f"{list(rows[0])}")

    kept, dropped = [], []
    for row in rows:
        match = resolves(row["LAS_NAME"])
        if match is None:
            dropped.append(row["Pole"])
            continue
        row["LAS_NAME"] = match
        kept.append(row)
    if dropped:
        print(f"WARN: dropped {len(dropped)} seed row(s) with no staged crop:"
              f" {dropped[:10]}{' ...' if len(dropped) > 10 else ''}")
    if not kept:
        sys.exit("no seed rows survived LAS_NAME validation - "
                 "crop names and CSV disagree")

    seed_dir = args.run_dir / "03_pole_vec_body"
    seed_dir.mkdir(parents=True, exist_ok=True)
    seed_csv = seed_dir / "polevec_pole_tops.csv"
    with open(seed_csv, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=required, extrasaction="ignore")
        w.writeheader()
        w.writerows(kept)
    print(f"seed CSV: {seed_csv}  ({len(kept)} pole(s))")

    # --- runtime control ---------------------------------------------------
    control = args.run_dir / "PoleVec_control_runtime.yml"
    control.write_text(
        CONTROL_TEMPLATE.format(crs=args.crs, threads=args.las_threads))
    print(f"control : {control}  (CRS: {args.crs}, FULL mode)")

    run_posix = str(args.run_dir.resolve()).replace("\\", "/")
    print("\nRun pole-vec with:\n")
    print(DOCKER_CMD.format(run_dir=run_posix))
    print("Then verify PoleVec/Combined/Grp0_Body_Lines.shp + "
          "Grp0_Parabola_Wires.shp + catenary.shp exist (exit 0 alone "
          "proves nothing).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
